HIV data cleaning 
=================

This script is used to load and clean the raw HIV related data from various sources.
These data are primarily used for the HIV cascade calculations. The resulting cleaned 
data sets are saved as dataframes in csv files in the
~/Evaluation\_Modelling/project\_care\_cascades/data/
folder. 


```{r initialization}
# Clear workspace
rm(list=ls()) 

# Libraries for data manipulation
require(readxl)
require(dplyr)
require(tidyr)
require(utils)

# Set working directory
setwd(file.path(path.expand("~/"),"Documents","Research","!Evaluation_Modelling","project_care_cascades","code"))

# Base directory
basePath <- "~/Documents/Research/!Evaluation_Modelling/project_care_cascades/"
cleanDataFolder <- file.path("..","data")

# Primary script parameters
dataYear <- 2013

```

## HIV Notifications

```{r notifications}
# Data directories and files
rawdata <- file.path(path.expand("~/"),"Documents","Research","!Evaluation_Modelling","data",
                     paste("rawHIVnotifications-", toString(dataYear), ".xls",sep=""))

# Load the raw HIV notifications file and clean it up
hivdata <- read_excel(rawdata, na = "NA")

# Extract what we wnat and clean it up

colnames(hivdata)[4] <- "dob"
colnames(hivdata)[5] <- "datediagnosis"
colnames(hivdata)[7] <- "exposure"

# Convert date format columns to date strings
hivdata$dob <- as.Date(hivdata$dob)
hivdata$datediagnosis <- as.Date(hivdata$datediagnosis)
hivdata$datedeath <- as.Date(hivdata$datedeath)

# Replace codes with easier to use strings - so we don't have to look up what thing mean
hivdata[hivdata$sex ==1,]$sex <- "male" 
hivdata[hivdata$sex ==2,]$sex <- "female" 
hivdata[hivdata$sex ==3,]$sex <- "transgender" 
hivdata[hivdata$sex ==0,]$sex <- "unknown" 

states <- c("act","nsw","nt","qld","sa","tas","vic","wa")
for(ii in 1:8){
  hivdata[hivdata$state == ii,]$state <- states[ii]
}

# Reclassification of exposure to the broad surveillance categories - may need to change manually
hivdata[hivdata$exposure == "1A",]$exposure <- "msm"
hivdata[hivdata$exposure == "1A3A",]$exposure <- "msm-idu"
hivdata[hivdata$exposure == "1A3B",]$exposure <- "msm"
hivdata[hivdata$exposure == "1A3C",]$exposure <- "msm"
hivdata[hivdata$exposure == "1B",]$exposure <- "bisex-male"
hivdata[hivdata$exposure == "1B3A",]$exposure <- "bisex-male-idu"
hivdata[hivdata$exposure == "1B3B",]$exposure <- "bisex-male"
hivdata[hivdata$exposure == "1C2A",]$exposure <- "hetero"
hivdata[hivdata$exposure == "1C2A2B",]$exposure <- "hetero"
hivdata[hivdata$exposure == "1C2B",]$exposure <- "hetero"
hivdata[hivdata$exposure == "1C2C",]$exposure <- "hetero"
hivdata[hivdata$exposure == "1C2D",]$exposure <- "hetero"
hivdata[hivdata$exposure == "1C2E",]$exposure <- "hetero"
hivdata[hivdata$exposure == "1C2F",]$exposure <- "hetero"
hivdata[hivdata$exposure == "1C2G",]$exposure <- "hetero"
hivdata[hivdata$exposure == "1C2H",]$exposure <- "hetero-unspecified"
hivdata[hivdata$exposure == "1C3A",]$exposure <- "hetero-idu"
hivdata[hivdata$exposure == "1C3A2B",]$exposure <- "hetero-idu"
hivdata[hivdata$exposure == "1C3A2E",]$exposure <- "hetero-idu"
hivdata[hivdata$exposure == "1C3B",]$exposure <- "hetero"
hivdata[hivdata$exposure == "1C3C",]$exposure <- "hetero"
hivdata[hivdata$exposure == "1D",]$exposure <- "high-prev-country"
hivdata[hivdata$exposure == "1E",]$exposure <- "unknown"
hivdata[hivdata$exposure == "1E3A",]$exposure <- "idu"
hivdata[hivdata$exposure == "1E3B",]$exposure <- "blood-recipient"
hivdata[hivdata$exposure == "1E3C",]$exposure <- "blood-recipient"
hivdata[hivdata$exposure == "1F",]$exposure <- "unknown"
hivdata[hivdata$exposure == "1F3A",]$exposure <- "unknown"
hivdata[hivdata$exposure == "1F3B",]$exposure <- "unknown"
hivdata[hivdata$exposure == "1F3C",]$exposure <- "unknown"
hivdata[hivdata$exposure == "4A",]$exposure <- "mtct"
hivdata[hivdata$exposure == "4B",]$exposure <- "mtct"
hivdata[hivdata$exposure == "4C",]$exposure <- "mtct"
hivdata[hivdata$exposure == "4D",]$exposure <- "mtct"
hivdata[hivdata$exposure == "4E",]$exposure <- "mtct"
hivdata[hivdata$exposure == "4F",]$exposure <- "mtct"
hivdata[hivdata$exposure == "4G",]$exposure <- "mtct"
hivdata[hivdata$exposure == "4J",]$exposure <- "mtct"
hivdata[hivdata$exposure == "4K",]$exposure <- "mtct"
hivdata[hivdata$exposure == "5A1",]$exposure <- "unknown"
hivdata[hivdata$exposure == "5A2",]$exposure <- "unknown"
hivdata[hivdata$exposure == "5A3",]$exposure <- "unknown"
hivdata[hivdata$exposure == "5A4",]$exposure <- "unknown"
hivdata[hivdata$exposure == "5B",]$exposure <- "unknown"

# Save cleaned hivdata
write.csv(hivdata, file = file.path(cleanDataFolder, paste("hivnotifications",toString(analysisYear),".csv", sep ="")))
```
