NNDSS notifications data extraction 
==================================

Richard T. Gray

This script is used to load and clean the raw NNDSS data received
from DOH and extract key estimates. These data are used for the STI cascade 
calculations. 


```{r Initialization}
# Restart R and set working directory to source file location

# Libraries for data manipulation
require(LeftysRpkg)
LoadLibrary(tidyverse)
LoadLibrary(readxl)
LoadLibrary(haven)

# Key folder paths
basePath <- file.path(dirname(getwd()))

# Primary script parameters - data year 
dataYear <- 2022
numYears <- 10

years <- (dataYear - numYears + 1):dataYear 

cascadeDataFolder <- file.path("C:", "Users", "rgray", "UNSW",
  "Australian Care Cascades - Documents")

```

```{r Load and clean data}
rawDataDirectory <- file.path("/", "SVR-NAS", "Public", "SERP", "Data", 
  "NNDSS", "SOURCE")

# Load the raw NNDSS notifications file 
rawDataFile <- file.path(rawDataDirectory, dataYear + 1,
  "Extract","NNDSS_MASTER.dta")

nndssdata <- read_dta(rawDataFile) 

# Extract the chlamydia, NG, syphilis and HCV notifications and key variables. 
# Clean up dataframe
# diseasecode (P:\SERP\Protocols\Data\NNDSS\NDSS_DISEASE_ID.docx)
# 7 = CT
# 11 = NG 
# HCV = c(40, 53) newly acquired and unspecified
# syphilis = c(47, 66, 67) (congenital, < 2 years, > 2 years or unspecified duration)

# CT
chlamdata <- tibble(nndssdata) %>%
  filter(diseasecode == 7) %>%
  select(age = AGE, sex = SEX, year = YEAR, remote = REMOTE) %>%
  mutate(sex = tolower(sex))

# Gono
ngdata <- tibble(nndssdata) %>%
  filter(diseasecode == 11) %>%
  select(age = AGE, sex = SEX, year = YEAR, remote = REMOTE,
    stisexualexposure, state = STATE) %>%
  mutate(sex = tolower(sex),
    sexualexposure = 0)

ngdata$sexualexposure[ngdata$stisexualexposure == "PERSON(S) OF OPPOSITE SEX ONLY"] <- 1
ngdata$sexualexposure[ngdata$stisexualexposure == "PERSON(S) OF SAME SEX ONLY"] <- 2
ngdata$sexualexposure[ngdata$stisexualexposure == "PERSON(S) OF BOTH SEXES"] <- 3
ngdata$sexualexposure[ngdata$stisexualexposure == "SEXUAL EXPOSURE UNKNOWN"] <- 4
ngdata$sexualexposure[ngdata$stisexualexposure == "NO SEXUAL CONTACT"] <- 5

# Syphilis
tpdata <- tibble(nndssdata) %>%
  filter(diseasecode %in% c(66)) %>% # Infectious syphilis only
  select(age = AGE, sex = SEX, year = YEAR, remote = REMOTE,
    stisexualexposure, state = STATE, diseasecode, indigenousstatus) %>%
  mutate(sex = tolower(sex),
    sexualexposure = 0) 

tpdata$sexualexposure[tpdata$stisexualexposure == "PERSON(S) OF OPPOSITE SEX ONLY"] <- 1
tpdata$sexualexposure[tpdata$stisexualexposure == "PERSON(S) OF SAME SEX ONLY"] <- 2
tpdata$sexualexposure[tpdata$stisexualexposure == "PERSON(S) OF BOTH SEXES"] <- 3
tpdata$sexualexposure[tpdata$stisexualexposure == "SEXUAL EXPOSURE UNKNOWN"] <- 4
tpdata$sexualexposure[tpdata$stisexualexposure == "NO SEXUAL CONTACT"] <- 5

# Hepatitis C
hcvdata <- tibble(nndssdata) %>%
  filter(diseasecode %in% c(40, 53)) %>%
  select(age = AGEGROUP, sex = SEX, year = YEAR, date = diagnosisdate) %>%
  # Appear to be no missing diagnosis dates
  mutate(age = ifelse(age == "", "Unknown", age),
    sex = tolower(sex),
    month = toupper(lubridate::month(date, label = TRUE)))

```

```{r Extract NG numbers}

# Number of NG notifications in males last three years
ngTotal <- ngdata %>% 
  filter(sex == "male", year %in% years) %>% 
  group_by(year) %>%
  summarise(n = n())

# Number in major cities
ngMajorCities <- ngdata %>% 
  filter(sex == "male", year %in% years, 
    remote == "Major Cities of Australia" ) %>% 
  group_by(year) %>%
  summarise(n = n())

# Number where region is missing
ngMissing <- ngdata %>% 
  filter(sex == "male", year %in% years, 
    remote == "Missing" ) %>% 
  group_by(year) %>%
  summarise(n = n())

# Number in other areas
ngOther <- tibble(year = years,
  n = ngTotal$n - ngMajorCities$n - ngMissing$n) %>%
  arrange(year)

# Merge notifications
ngMSMdiags <- ngTotal %>%
  rename(male = n) %>%
  left_join(ngMajorCities %>% rename(cities = n), by = "year") %>%
  left_join(ngOther %>% rename(regions = n), by = "year") %>%
  left_join(ngMissing  %>% rename(missing = n), by = "year")

# GBM numbers from enhanced data -----------------------------------------------

# Proportion of male diagnoses in GBM - major cities
ngMajorCities_known <- ngdata %>% 
  filter(sex == "male", year %in% years, 
    remote == "Major Cities of Australia", remote != "Missing") %>%
  filter(!is.na(sexualexposure)) %>% 
  filter(sexualexposure %in% c(1:3)) %>%
  group_by(year) %>%
  summarise(n = n())

ngGBMMajorCities_known <- ngdata %>% 
  filter(sex == "male", year %in% years, 
    remote == "Major Cities of Australia", remote != "Missing") %>%
  filter(!is.na(sexualexposure)) %>%
  filter(sexualexposure %in% c(2,3)) %>%
  group_by(year) %>%
  summarise(n = n())

propGBMcities <- ngGBMMajorCities_known$n/ngMajorCities_known$n

# Proportion of male diagnoses in GBM - non-Major cities
ngRegions_known <- ngdata %>% 
  filter(sex == "male", year %in% years,  
    remote != "Major Cities of Australia", remote != "Missing") %>%
  filter(!is.na(sexualexposure)) %>% 
  filter(sexualexposure %in% c(1:3)) %>%
  group_by(year) %>%
  summarise(n = n())

ngGBMRegions_known <- ngdata %>% 
  filter(sex == "male", year %in% years, 
    remote != "Major Cities of Australia", remote != "Missing" ) %>%
  filter(!is.na(sexualexposure)) %>%
  filter(sexualexposure %in% c(2,3)) %>%
  group_by(year) %>%
  summarise(n = n())

propGBMregions <- ngGBMRegions_known$n/ngRegions_known$n

# Add proportions to GBM diagnoses
ngMSMdiags <- ngMSMdiags %>%
  mutate(prop_cities = propGBMcities,
    prop_regions = propGBMregions)

# Write final data frame to cascades folder ------------------------------------
write.csv(ngMSMdiags, file = file.path(cascadeDataFolder, "OtherSTIs", 
  "Gonorrhoea", paste0("gbmNGnotifications-", dataYear, ".csv")), 
  row.names = FALSE)

```

```{r Proportion CT by region}

ctOverall <- chlamdata %>%
  filter(year %in% years, remote != "Missing") %>%
  group_by(year) %>%
  summarise(n = n())

ctUrban <- chlamdata %>%
  filter(year %in% years, remote %in% "Major Cities of Australia") %>%
  group_by(year) %>%
  summarise(n = n())

ctRegional <- chlamdata %>%
  filter(year %in% years, remote %in% c("Inner Regional Australia", 
    "Outer Regional Australia")) %>%
  group_by(year) %>%
  summarise(n = n())

ctRemote <- chlamdata %>%
  filter(year %in% years, 
    remote %in% c("Remote Australia", "Very Remote Australia")) %>%
  group_by(year) %>%
  summarise(n = n())

ctAlldiags <- ctOverall %>%
  rename(all = n) %>%
  left_join(ctUrban %>% rename(urban = n), by = "year") %>%
  left_join(ctRegional %>% rename(regional = n), by = "year") %>%
  left_join(ctRemote %>% rename(remote = n), by = "year")

# Add proportions
ctAlldiags <- ctAlldiags %>%
  mutate(prop_urban = urban / all) %>%
  mutate(prop_regional = regional / all) %>%
  mutate(prop_remote = remote / all)

# Write final data frame to cascades folder ------------------------------------
write.csv(ctAlldiags, file = file.path(cascadeDataFolder, "Chlamydia", 
  "data", paste0("CT_notification_proportions-", dataYear, ".csv")), 
  row.names = FALSE)

```

```{r Extract TP numbers Males}

# Number of tp notifications in males last three years
tpTotal <- tpdata %>% 
  filter(sex == "male", year %in% years) %>% 
  group_by(year) %>%
  summarise(n = n())
# print(tpTotal)

# Number in major cities
tpMajorCities <- tpdata %>% 
  filter(sex == "male", year %in% years, 
    remote == "Major Cities of Australia" ) %>% 
  group_by(year) %>%
  summarise(n = n())
# print(tpMajorCities)

# Number where region is missing
tpMissing <- tpdata %>% 
  filter(sex == "male", year %in% years, 
    remote == "Missing" ) %>% 
  group_by(year) %>%
  summarise(n = n())
# print(tpMissing)

# Number in other areas
tpOther <- tibble(year = years,
  n = tpTotal$n - tpMajorCities$n - tpMissing$n) %>%
  arrange(year)
# print(tpOther)

# Merge notifications
tpMSMdiags <- tpTotal %>%
  rename(male = n) %>%
  left_join(tpMajorCities %>% rename(cities = n), by = "year") %>%
  left_join(tpOther %>% rename(regions = n), by = "year") %>%
  left_join(tpMissing  %>% rename(missing = n), by = "year")

# GBM numbers from enhanced data -----------------------------------------------

# Proportion of male diagnoses in GBM - major cities
tpMajorCities <- tpdata %>% 
  filter(sex == "male", year %in% years, 
    remote == "Major Cities of Australia", remote != "Missing") %>%
  filter(!is.na(sexualexposure)) %>% 
  filter(sexualexposure %in% c(1:3)) %>%
  group_by(year) %>%
  summarise(n = n())

tpGBMMajorCities <- tpdata %>% 
  filter(sex == "male", year %in% years, 
    remote == "Major Cities of Australia", remote != "Missing") %>%
  filter(!is.na(sexualexposure)) %>%
  filter(sexualexposure %in% c(2,3)) %>%
  group_by(year) %>%
  summarise(n = n())

propGBMcitiesTP <- tpGBMMajorCities$n/tpMajorCities$n

# Proportion of male diagnoses in GBM - non-Major cities
tpRegions <- tpdata %>% 
  filter(sex == "male", year %in% years,  
    remote != "Major Cities of Australia", remote != "Missing") %>%
  filter(!is.na(sexualexposure)) %>% 
  filter(sexualexposure %in% c(1:3)) %>%
  group_by(year) %>%
  summarise(n = n())

tpGBMRegions <- tpdata %>% 
  filter(sex == "male", year %in% years, 
    remote != "Major Cities of Australia", remote != "Missing" ) %>%
  filter(!is.na(sexualexposure)) %>%
  filter(sexualexposure %in% c(2,3)) %>%
  group_by(year) %>%
  summarise(n = n())

propGBMregionsTP <- tpGBMRegions$n/tpRegions$n

# Add proportions to GBM diagnoses
tpMSMdiags <- tpMSMdiags %>%
  mutate(prop_cities = propGBMcitiesTP,
    prop_regions = propGBMregionsTP)

# Write final data frame to cascades folder ------------------------------------
write.csv(tpMSMdiags, file = file.path(cascadeDataFolder, "OtherSTIs", 
  "syphilis", paste0("gbmTPnotifications-", dataYear, ".csv")), 
  row.names = FALSE)

```

# Testing code ===============================================================

```{r Extract TP numbers Indigenous}

tpdataPop <- tpdata %>% 
  # Tidy up indigenous status
  mutate(indigenousstatus = ifelse(is.na(indigenousstatus), 9, 
    indigenousstatus)) %>%
  mutate(population = "") %>%
  mutate(population = ifelse(indigenousstatus == 4, "non-indigenous", population)) %>%
  mutate(population = ifelse(indigenousstatus == 9, "missing", population)) %>%
  mutate(population = ifelse(indigenousstatus %in% c(1,2,3), "indigenous",
    population))

tpTotalMissing <- tpdataPop %>% 
  filter(year == dataYear) %>% 
  group_by(state, population) %>%
  summarise(n = n()) 
print(tpTotalMissing)
print(sum(tpTotalMissing$n))

# NSW, QLD, and Vic have missing
tpMissing <- tpTotalMissing %>% filter(state == "VIC")

round(filter(tpMissing, population == "indigenous")$n + 
  filter(tpMissing, population == "missing")$n * 
  filter(tpMissing, population == "indigenous")$n /
  (filter(tpMissing, population == "indigenous")$n + 
      filter(tpMissing, population == "non-indigenous")$n))

# NSW = 105
# VIC = 54
# QLD = 274
totalFromMissing <- 105 + 54 + 274

tpTotalIndigenous <- sum((tpTotalMissing %>%
  filter(!(state %in% c("NSW", "VIC", "QLD")), population == "indigenous"))$n) + totalFromMissing
print(tpTotalIndigenous)

  
# Number of tp notifications in last three years
tpTotal <- tpdataPop %>% 
  filter(year %in% c(dataYear, dataYear - 1, dataYear - 2)) %>% 
  group_by(year) %>%
  summarise(n = n())
print(tpTotal)


```

# Once off extractions (not used for the ASR)

```{r NG notifications for young people}

ngTest <- ngdata %>% 
  filter(year >= 2010) %>%
  select(age, sex, year) %>%
  group_by(age, sex, year) %>%
  summarise(notifications = n()) %>%
  ungroup()

# Missing data:
# ngTest %>% filter(age == -1) %>% nrow() # 25 with missing age
# ngTest %>% filter(sex == -1) %>% nrow() # 0 with missing sex

ngTest <- ngTest %>% 
  filter(age != -1) 

# Now calculate groups we need

ageSeq <- (0:15)
sexTarget <- "female"

ngDiags <- function(sexTarget, ageSeq, label) {
  
  df <- ngTest %>%
    filter(sex == sexTarget, age %in% ageSeq) %>%
    group_by(year) %>%
    summarise(!!label := sum(notifications)) 
  
  return(df)
  
}

# Females
ngFemales1 <- ngDiags("female", (0:15), "female < 15 yrs")
ngFemales2 <- ngDiags("female", (15:19), "female 15-19 yrs")
ngFemales3 <- ngDiags("female", (20:24), "female 20-24 yrs")
ngFemales4 <- ngDiags("female", (25:29), "female 25-29 yrs")
ngFemales5 <- ngDiags("female", (30:34), "female 30-34 yrs")
ngFemales6 <- ngDiags("female", (35:150), "female > 34 yrs")
ngFemales7 <- ngDiags("female", (0:150), "female all")

# Males
ngMales1 <- ngDiags("male", (0:15), "male < 15 yrs")
ngMales2 <- ngDiags("male", (15:19), "male 15-19 yrs")
ngMales3 <- ngDiags("male", (20:24), "male 20-24 yrs")
ngMales4 <- ngDiags("male", (25:29), "male 25-29 yrs")
ngMales5 <- ngDiags("male", (30:34), "male 30-34 yrs")
ngMales6 <- ngDiags("male", (35:150), "male > 34 yrs")
ngMales7 <- ngDiags("male", (0:150), "male all")

# Merge data frames
ngNotifications <- bind_cols(ngMales1, select(ngMales2, -year), 
  select(ngMales3, -year), select(ngMales4, -year), 
  select(ngMales5, -year), select(ngMales6, -year), 
  select(ngMales7, -year), select(ngFemales1, -year),
  select(ngFemales2, -year), select(ngFemales3, -year),
  select(ngFemales4, -year), select(ngFemales5, -year),
  select(ngFemales6, -year), select(ngFemales7, -year))

write.csv(ngNotifications, "notifications-ng.csv")

```

```{r Monthly HCV notifications}

monthlyHCV <- hcvdata %>% 
  group_by(age, year, month) %>%
  summarise(n = n()) %>%
  filter(year >= 2009) %>%
  select(year, month, everything()) %>%
  spread(age, n) 

monthlyHCV[is.na(monthlyHCV)] <- 0

write.csv(monthlyHCV, file = "monthlyHCV_2012-2021.csv")


```


